/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: prw.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "prw.pb-c.h"
void   write_request__init
                     (WriteRequest         *message)
{
  static const WriteRequest init_value = WRITE_REQUEST__INIT;
  *message = init_value;
}
size_t write_request__get_packed_size
                     (const WriteRequest *message)
{
  assert(message->base.descriptor == &write_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t write_request__pack
                     (const WriteRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &write_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t write_request__pack_to_buffer
                     (const WriteRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &write_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WriteRequest *
       write_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WriteRequest *)
     protobuf_c_message_unpack (&write_request__descriptor,
                                allocator, len, data);
}
void   write_request__free_unpacked
                     (WriteRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &write_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   time_series__init
                     (TimeSeries         *message)
{
  static const TimeSeries init_value = TIME_SERIES__INIT;
  *message = init_value;
}
size_t time_series__get_packed_size
                     (const TimeSeries *message)
{
  assert(message->base.descriptor == &time_series__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t time_series__pack
                     (const TimeSeries *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &time_series__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t time_series__pack_to_buffer
                     (const TimeSeries *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &time_series__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TimeSeries *
       time_series__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TimeSeries *)
     protobuf_c_message_unpack (&time_series__descriptor,
                                allocator, len, data);
}
void   time_series__free_unpacked
                     (TimeSeries *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &time_series__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   label__init
                     (Label         *message)
{
  static const Label init_value = LABEL__INIT;
  *message = init_value;
}
size_t label__get_packed_size
                     (const Label *message)
{
  assert(message->base.descriptor == &label__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t label__pack
                     (const Label *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &label__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t label__pack_to_buffer
                     (const Label *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &label__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Label *
       label__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Label *)
     protobuf_c_message_unpack (&label__descriptor,
                                allocator, len, data);
}
void   label__free_unpacked
                     (Label *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &label__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sample__init
                     (Sample         *message)
{
  static const Sample init_value = SAMPLE__INIT;
  *message = init_value;
}
size_t sample__get_packed_size
                     (const Sample *message)
{
  assert(message->base.descriptor == &sample__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sample__pack
                     (const Sample *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sample__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sample__pack_to_buffer
                     (const Sample *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sample__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sample *
       sample__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sample *)
     protobuf_c_message_unpack (&sample__descriptor,
                                allocator, len, data);
}
void   sample__free_unpacked
                     (Sample *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sample__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor write_request__field_descriptors[1] =
{
  {
    "timeseries",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(WriteRequest, n_timeseries),
    offsetof(WriteRequest, timeseries),
    &time_series__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_request__field_indices_by_name[] = {
  0,   /* field[0] = timeseries */
};
static const ProtobufCIntRange write_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor write_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WriteRequest",
  "WriteRequest",
  "WriteRequest",
  "",
  sizeof(WriteRequest),
  1,
  write_request__field_descriptors,
  write_request__field_indices_by_name,
  1,  write_request__number_ranges,
  (ProtobufCMessageInit) write_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor time_series__field_descriptors[2] =
{
  {
    "labels",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TimeSeries, n_labels),
    offsetof(TimeSeries, labels),
    &label__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "samples",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TimeSeries, n_samples),
    offsetof(TimeSeries, samples),
    &sample__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned time_series__field_indices_by_name[] = {
  0,   /* field[0] = labels */
  1,   /* field[1] = samples */
};
static const ProtobufCIntRange time_series__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor time_series__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TimeSeries",
  "TimeSeries",
  "TimeSeries",
  "",
  sizeof(TimeSeries),
  2,
  time_series__field_descriptors,
  time_series__field_indices_by_name,
  1,  time_series__number_ranges,
  (ProtobufCMessageInit) time_series__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor label__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Label, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Label, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned label__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange label__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor label__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Label",
  "Label",
  "Label",
  "",
  sizeof(Label),
  2,
  label__field_descriptors,
  label__field_indices_by_name,
  1,  label__number_ranges,
  (ProtobufCMessageInit) label__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sample__field_descriptors[2] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Sample, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Sample, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sample__field_indices_by_name[] = {
  1,   /* field[1] = timestamp */
  0,   /* field[0] = value */
};
static const ProtobufCIntRange sample__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sample__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Sample",
  "Sample",
  "Sample",
  "",
  sizeof(Sample),
  2,
  sample__field_descriptors,
  sample__field_indices_by_name,
  1,  sample__number_ranges,
  (ProtobufCMessageInit) sample__init,
  NULL,NULL,NULL    /* reserved[123] */
};
