#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/junos-common-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module junos-common-types.yang


class ns(object):
    hash = 103271231

    id = "_ned-junos-23.1-yang-nc-1.0:ned-junos-23.1-yang-nc-1.0#http://yang.juniper.net/junos/common/types"

    uri = "_ned-junos-23.1-yang-nc-1.0:ned-junos-23.1-yang-nc-1.0#http://yang.juniper.net/junos/common/types"

    prefix = "jt"

