name: Build & Test

on:
  push:


jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository code"
        uses: actions/checkout@v3
#      - name: "Install acton"
#        run: |
#          wget https://github.com/actonlang/acton/releases/download/tip/acton_tip_amd64.deb
#          sudo dpkg -i acton_*.deb
      - name: "Install acton"
        run: |
          wget -q -O - https://apt.acton-lang.io/acton.gpg | sudo apt-key add -
          echo "deb [arch=amd64] http://apt.acton-lang.io/ stable main" | sudo tee /etc/apt/sources.list.d/acton.list
          sudo apt-get update
          sudo apt-get install -qy acton
      - name: "Build"
        run: |
          actonc build
      - name: "Test"
        run: |
          make test

#  test-macos:
#    runs-on: macos-12
#    steps:
#      - name: "Check out repository code"
#        uses: actions/checkout@v3
#      - name: "Install acton"
#        run: |
#          wget https://github.com/actonlang/acton/releases/download/tip/acton-darwin-x86_64.tar.bz2
#          tar jxvf $(ls acton-darwin*.tar.bz2 | tail -n1)
#          echo "PATH=$(pwd)/acton/bin:$PATH" >> $GITHUB_ENV
#      - name: "Build"
#        run: |
#          actonc build
