name: Keep acton-next up to date

# Trigger job on pushes to main branch
on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: "Configure git"
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: "Rebase acton-next on main"
      run: |
        git checkout acton-next
        git rebase main

    - name: "Force push to acton-next"
      run: git push origin acton-next --force
